version: '3'

services:
  app:
    build: .
    image: ghcr.io/democraciaenred/datosenfuga-next:latest
    env_file:
      - .env.local 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules      
    ports:
      - 3000:3000
    command: npm run dev