version: '3'

services:
  app:
    build:
      context: .
    image: democraciaenred/datosenfuga-next:latest
    env_file:
      - .env.local
    volumes: 
      - .:/usr/src/app    
    ports:
      - 3000:3000