import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans'
})
const nippo = localFont({
  src: [
    {
      path: './fonts/NIPPO-EXTRALIGHT.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/NIPPO-LIGHT.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/NIPPO-REGULAR.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NIPPO-MEDIUM.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/NIPPO-BOLD.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-nippo',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${nippo.variable} ${openSans.className} ${inter.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
