name: Merge to Deploy on Release

on:
  release:
    types: [created]

jobs:
  merge_to_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into deploy
        run: |
          git checkout deploy
          git merge main --no-ff --no-edit
          git push origin deploy